### PR TITLE
[WIP] Implement eventstudies functionality

### PR DESCRIPTION
**Pull request by asinghvi17**
Here's an MWE which is functional now:
```julia
using TSFrames
using EventStudies
using Makie

# first, define the TSFrame
ts1 = TSFrame(
    DataFrame(
        :Index => 1:11,
        :var1 => vcat(LinRange(0, 1, 5), ones(6)),
        :var2 => vcat(LinRange(0, 1, 6), ones(5)),
    )
)

# For convenience, I've directly referred to everything from EventStudies.jl as `EventStudies.*`.
# However, these are all exported, so you don't have to do that.

phystime_returns_ts, statuses = EventStudies.to_eventtime_windowed(levels_to_returns(ts1), [:var1 => 5, :var2 => 6], 2)
phystime_cum_ts = EventStudies.remap_cumsum(phystime_returns_ts)
confints = EventStudies.inference(EventStudies.BootstrapInference(), phystime_cum_ts)

f, a, p = series(phystime_cum_ts.Index, Matrix(phystime_cum_ts)'; axis = (xlabel = "Time relative to event", ylabel = "Cumulative difference (%)"))
band!(phystime_cum_ts.Index, confints[2], confints[3])
lines!(phystime_cum_ts.Index, confints[1])
Makie.current_figure()

```
download-8

To add the package, simply `]add https://github.com/asinghvi17/EventStudies.jl#as/eventstudies`.

### CODE REVIEW

**Comment by asinghvi17** [comment]
With the new script in `examples/nifty.jl`, these are the plots I get:
download-11


download-9
There are some differences between these and the plots made by eventstudies in R, so I'll have to see exactly what is going wrong.

**Comment by chiraganand** [comment]
This is a great start @asinghvi17!

Do you want to commit test cases also in this PR while comparing the output with that of R package: https://github.com/xkdr/eventstudies?

**Comment by asinghvi17** [comment]
Yeah, I'll probably gradually bring those tests in as I implement functionality.  I've made some slightly different API choices, so all the tests may not be directly comparable.

**Comment by asinghvi17** [comment]
Here's a basic diagram of how the package works now.  Hexagons are functions, squares are objects.

d2

**Comment by asinghvi17** [comment]
The PR is unfinished, but I need to merge this to master so docs can begin to deploy.  I'll probably merge this today if CI is green.

**Pull request merged**
